# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repog < Formula
  desc "AI-powered knowledge base for your GitHub repositories"
  homepage "https://github.com/hackastak/repog"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hackastak/repog/releases/download/v0.2.0/repog_0.2.0_darwin_amd64.tar.gz"
    sha256 "c5eedbab0a46ef3dd7a0758d2e7a2a44386e7ecf543de62831ba6f601ba37bca"

    define_method(:install) do
      bin.install "repog"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hackastak/repog/releases/download/v0.2.0/repog_0.2.0_darwin_arm64.tar.gz"
    sha256 "66772d330c35a833c54ffd1a520bc2cc6ca963bc6dbecccd1b4b2e5c8e489726"

    define_method(:install) do
      bin.install "repog"
    end
  end

  test do
    system "#{bin}/repog --help"
  end
end
