# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repog < Formula
  desc "AI-powered knowledge base for your GitHub repositories"
  homepage "https://github.com/hackastak/repog"
  version "0.2.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hackastak/repog/releases/download/v0.2.4/repog_0.2.4_darwin_amd64.tar.gz"
    sha256 "ae0e95a9e9b5137907ca05a2b6fcf390db0b7bd7e37c8b17c7560b09c0a66832"

    define_method(:install) do
      bin.install "repog"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hackastak/repog/releases/download/v0.2.4/repog_0.2.4_darwin_arm64.tar.gz"
    sha256 "0fb680b86c3fde2d7b50459e5a2d85f8ccc524fec0c4383675e49a2a3590da71"

    define_method(:install) do
      bin.install "repog"
    end
  end

  test do
    system "#{bin}/repog --help"
  end
end
