# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repog < Formula
  desc "AI-powered knowledge base for your GitHub repositories"
  homepage "https://github.com/hackastak/repog"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/hackastak/repog/releases/download/v0.1.0/repog_0.1.0_darwin_amd64.tar.gz"
    sha256 "cbdac8054be998b7f7cfd7eac3927b0651b759e740845edefee0a8f4b04133c2"

    define_method(:install) do
      bin.install "repog"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/hackastak/repog/releases/download/v0.1.0/repog_0.1.0_darwin_arm64.tar.gz"
    sha256 "e1da3e9f3f2b2f2a580c16096d8f82a1f8302528e3f7fa7069cd658aadaf7993"

    define_method(:install) do
      bin.install "repog"
    end
  end

  test do
    system "#{bin}/repog --help"
  end
end
